app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app import views

urlpatterns = [
    url(r'^home/', views.home,name="home"),
    url(r'^market/$', views.market,name="market"),
    url(r'^market/(\d+)/(\d+)/(\d+)', views.market_with_param,name="marketWP"),
    url(r'^cart/', views.cart,name="cart"),
    url(r'^mine/', views.mine,name="mine"),
    url(r'^register/', views.register,name="register"),
    url(r'^logout/', views.logout,name="logout"),
    url(r'^checkUser/', views.checkUser,name="checkUser"),
    url(r'^logoUser/', views.logoinUser,name="logoUser"),
    url(r'^addToCart/', views.addToCart,name="addToCart"),
    url(r'^subToCart/', views.subToCart,name="subToCart"),
    url(r'^changeSelectStatus/', views.changeSelectStatus,name="changeSelectStatus"),
    url(r'^addCartNum/', views.addCartNum,name="addCartNum"),
    url(r'^subCartNum/', views.subCartNum,name="subCartNum"),
    url(r'^chanageCartSelect/', views.chanageCartSelect,name="chanageCartSelect"),
    url(r'^generateOrder/', views.generateOrder,name="generateOrder"),
    url(r'^orderInfo/(.+)', views.orderInfo,name="orderInfo"),
    url(r'^chageOrderStatus', views.chageOrderStatus,name="chageOrderStatus"),
    url(r'^nopayOrder', views.nopayOrder,name="nopayOrder"),
]

axf1804/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include("app.urls",namespace="axf")),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">#}
    <link rel="stylesheet" type="text/css" href="{% static 'css/swiper.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'  %}">
    {% block extCSS %}
    
    {% endblock %}

</head>
<body>
    {% block header %}
    
    {% endblock %}
    
    {% block content %}
    
    {% endblock %}
    
    {% block footer %}
    
    {% endblock %}

<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/swiper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
{% block extJS %}

{% endblock %}

</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
{% endblock %}


{% block header %}
    <header>

    </header>
{% endblock %}




{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt> <span></span></dt>
                <dd>主页</dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' %}" class="market">
            <dl>
                <dt><span></span></dt>
                <dd>闪购</dd>
            </dl>
        </a>
        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt><span></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt><span></span></dt>
                <dd>我的</dd>
            </dl>
        </a>

    </footer>
{% endblock %}