app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app import views

urlpatterns = [
    url(r'^home/', views.home,name="home"),
    url(r'^market/$', views.market,name="market"),
    url(r'^market/(\d+)/(\d+)/(\d+)', views.market_with_param,name="marketWP"),
    url(r'^cart/', views.cart,name="cart"),
    url(r'^mine/', views.mine,name="mine"),
    url(r'^register/', views.register,name="register"),
    url(r'^logout/', views.logout,name="logout"),
    url(r'^checkUser/', views.checkUser,name="checkUser"),
    url(r'^logoUser/', views.logoinUser,name="logoUser"),
    url(r'^addToCart/', views.addToCart,name="addToCart"),
    url(r'^subToCart/', views.subToCart,name="subToCart"),
    url(r'^changeSelectStatus/', views.changeSelectStatus,name="changeSelectStatus"),
    url(r'^addCartNum/', views.addCartNum,name="addCartNum"),
    url(r'^subCartNum/', views.subCartNum,name="subCartNum"),
    url(r'^chanageCartSelect/', views.chanageCartSelect,name="chanageCartSelect"),
    url(r'^generateOrder/', views.generateOrder,name="generateOrder"),
    url(r'^orderInfo/(.+)', views.orderInfo,name="orderInfo"),
    url(r'^chageOrderStatus', views.chageOrderStatus,name="chageOrderStatus"),
    url(r'^nopayOrder', views.nopayOrder,name="nopayOrder"),
]

axf1804/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include("app.urls",namespace="axf")),
]

templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'app/mine/mine.css' %}">
{% endblock %}


{% block content %}
    <div id="mine">
        <div class="fixed">
            {% if is_login %}

                   <img src="{{ imgPath }}" alt="">
                   <p>{{ user.username }}</p>
                {% else %}
                  <span style="color: red" class="glyphicon glyphicon-user"></span>
                  <p><a href="{% url 'axf:logoUser' %}">未登录</a></p>
            {% endif %}

            <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>

            {% if is_login %}
                {% else %}
                 <a id="regis" href="{% url 'axf:register' %}">注册</a>
            {% endif %}

            <p><span class="glyphicon glyphicon-heart"></span>商品收藏</p>
        </div>
        <section class="mine">
            <p>
                <span>我的订单</span>
                <a href="#">查看全部订单</a>
            </p>
            <nav id="nav">
                <ul>
                    <li>
                        <a href="{% url 'axf:nopayOrder' %}">
                        <dl>
                            <dt><span class="glyphicon glyphicon-usd"></span>
                                {% ifequal nopay 0 %}
                                    {% else %}
                                      <span style="color: red" class="badge">{{ nopay }}</span>
                                {% endifequal %}
                            </dt>
                            <dd>待付款</dd>
                        </dl>
                        </a>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-envelope"></span>
                             {% ifequal payed 0 %}
                                    {% else %}
                                      <span style="color: red" class="badge">{{ payed }}</span>
                                {% endifequal %}

                            </dt>
                            <dd>待收货</dd>
                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                            <dd>待评价</dd>
                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-transfer"></span></dt>
                            <dd>退款/售后</dd>
                        </dl>

                    </li>
                </ul>

            </nav>

            <menu>
                <ul>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                                <dd>积分商城</dd>
                            </dl>
                        </a>

                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>

                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-import"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>

                    </li>
                    <li>
                        <a href="">
                            <dl>
                                <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                                <dd>客服/反馈</dd>
                            </dl>
                        </a>

                    </li>
                    <li>
                        <a href=""></a>
                        <dl>
                            <dt><span class="glyphicon glyphicon-asterisk"></span></dt>
                            <dd>关于我们</dd>
                        </dl>
                        </a>

                    </li>

                </ul>


            </menu>
            <p>
                <a href="{% url  'axf:logout' %}">退出账号</a>
            </p>


        </section>


    </div>

{% endblock %}